<Project Sdk="Ignitron.Mod.Sdk/0.8.5">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>shaping_extended_mod</AssemblyName>
        <RootNamespace>ShapingExtended</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <!-- Place assets under the mod ID at build output. -->
        <Content Include="Content\**\*.*"
             CopyToOutputDirectory="PreserveNewest"
             Link="ignitron\$(AssemblyName)\%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>
</Project>
